### ISSUE TITLE
18 回望K8S 白话容器

### ISSUE THREAD

**Issue by pinkhello** [pinkhello/pinkhello.github.io#6]
https://pinkhello.github.io/posts/18-%E5%9B%9E%E6%9C%9Bk8s-%E7%99%BD%E8%AF%9D%E5%AE%B9%E5%99%A8/

**Comment by PinkHello** [comment]
可怜的容器，被Namespace欺骗，又被Cgroups限制，在这样的环境下，还发挥着自己生命的意义-与应用程序同生命周期，同生共死～
